language: node_js
node_js:
  - '6'

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # - npm run update-webdriver
  # - sleep 1 # give server time to start

script:
  - npm run eslint
  - npm run stylint
  - npm run test-single-run
  - npm run report-coverage
  # - node_modules/.bin/protractor e2e-tests/protractor.conf.js --browser=firefox
